---
output: html_document
---
# Classes 

## Statistical and Data Sciences

Intro to Data Science (A-)

Calculus II (B)

Communicating With Data (S)*

Statistical Methods:Undergrad (S)*

Intro Comp Sci Programming (A)

Linear Algebra (B+)

Multiple Regression (A)

Research Design and Analysis (A)

## Government

Intro to Political Thinking (A-)

International Politics (S)*

Intro to Comparative Politics (A-)

American Constitutional Law (B+)

Global Cities (A-)

Conceptualizing Democracy (A)

Gender Perspectives on Human Rights (A)**

Humanitarian Law & Armed Conflict (A-)**

Migrant & Refugee Childrn in Europe (A)**

## Others

Performing the Self in the Digital Age Writing Seminar (A)

Astronomy & Public Policy (S)*

High Intermediate French (A-)

The Meaning of Life (A)

Sustainability and Social-Ecological Systems (A)

Danish Language and Culture (A-)**

Ethical & Scientific Legacy of the Nazi Medical Crimes (A-)**




### *COVID-19 interruption, all classes S/U

### ** Study Abroad in Denmark (Spring 2022)




















