---
output: html_document
font-family: 'Times New Roman'
---

    I’d like to first start by saying that the world we live in is extremely unfair. Second, I would like you to know that I am on my way to being what Plato calls a “philosopher-queen.”

    I’m not going to tell you my life story or anything like that, but I’m going to give you the basics so that you have some context. I was born into a dirt-poor family. And I quite literally mean dirt poor. My dad is a farmer. My parents are both of the bronze class. I guess I should explain that. 
    
    In my society, this guy named Plato makes all the rules and one of his rules is that every person is born with a metal inside of them which determines their future. In school we get taught that “the god who made you mixed some gold into those who are adequately equipped to rule…silver in those who are auxiliaries and iron and bronze in the farmers and other craftsmen” (Plato 1992, 415a). Anybody can be born of any metal. Take me for example, my parents both have bronze in them, but I was born with gold inside me. Now you might be wondering how in the heck they find out what metal is inside of us. No, they do not cut us open, but they find out through how we do in school. 

    In my world, everyone gets the same education, at first. As you get older and your metal is determined, you either stop your education, and work, or keep learning. In my opinion that’s not fair. How come my younger brother had to go work with my dad and I get to keep going with my education? He loves school, he’s just not that good at reading. That doesn’t seem right to me, but as Plato says, “If an offspring… should be found to have a mixture of iron or bronze, they must not pity him in any way, but give him the rank appropriate to his nature and drive him out to join the craftsmen and farmers” (Plato 1992, 415b). In order for our society to function we need laborers so that way the ruling class, which I guess is me now, can go about our work unbothered by such trivial things.
    
  
    Here’s the thing, none of us golds actually want to be rulers. We would all really rather just worry about the trivial things and stick to our books. But I guess that’s the entire point. When we were told that we had gold inside of us, Plato told us that “in a city of good men, if it came into being, the citizens would fight in order not to rule…There it would be quite clear that anyone who is really a true ruler doesn't by nature seek his own advantage but that of his subjects” (Plato 1992, 347d). We are who we are precisely because we don’t want what we have. And I guess when it comes down to it, that works out. The people I am surrounded with truly care about the future of our society and everyone in it. Almost every day we talk about why we have to rule. This comment by Plato comes up quite often, “the greatest punishment, if one isn’t willing to rule, is to be ruled by someone worse than oneself. And I think it’s the fear of this that makes decent people rule when they do” (Plato 1992, 347c). We are supposed to hate our job, and I do. But some of my classmates extra hate me, and it doesn’t make this forcing-myself-to-rule thing any easier.
	  
    I’m the only girl in our year and I can never get a straight answer out of Plato about how he feels about women. He goes around claiming that “one sex is much superior in pretty well everything,” but then follows up with “many women are better than many men in many things” (Plato 1992, 453d). That confuses me to no end. I think what he is actually trying to say is that men are actually better at everything in every way, but we need women so that our society can continue to reproduce and grow. But I’m just a philosopher-queen in the making, what would I know. 
    
    I will give Plato one good thing on the topic of women. Despite all his sexist comments, he does argue that “if we use women for the same things as men, they must also be taught the same things” (Plato 1992, 450e). Because of this idea, I was able to obtain the same education as my younger brother and even rise above him in our society. I don’t know of any other society like that, at least in the time where I’m writing from. I wonder what it’ll be like in 2019. Maybe there will be some nasty old autocratic leader who really hates women and convinces enough of the country to hate them too and then gets elected democratically, but not really… just a thought. 
    
    I don’t know what is to come for me in this society. I wonder if I will be increasingly pushed aside because I am a woman, or if I will be held in higher regard because of my seemingly more difficult path to get here. All I know is that it is my duty to my family and my society to rule in the best way that I can. 

Word Count: 908

Bibliography
1.	Plato, et al. Plato: Republic. Hackett Publishing Company, 1992.


